name: pokedex
description: Pokedex

version: 1.0.0+1

scripts:
  mobx: "flutter pub run build_runner watch --delete-conflicting-outputs"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  responsive_widgets: ^2.0.1
  md2_tab_indicator: ^1.0.2
  simple_animations: ^1.3.11
  sliding_sheet: ^0.3.1
  cached_network_image: ^2.0.0
  flutter_staggered_animations: ^0.1.2
  dio: ^3.0.9
  flutter_mobx: ^1.1.0
  mobx: ^1.1.1
  flutter_modular: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.0.3
  build_runner: ^1.8.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/pokeball_black.png
    - assets/images/pokeball_white.png
  fonts:
    - family: Google
      fonts:
        - asset: assets/fonts/Product_Sans_Regular.ttf
        - asset: assets/fonts/Product_Sans_Bold.ttf
          weight: 700